# Generated by Django 4.2.4 on 2023-08-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_delete_usercreation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
