# Generated by Django 4.2.4 on 2023-08-10 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
